export const C = {
  bg:      '#0a0a0f',
  surface: '#13131a',
  card:    '#1c1c27',
  border:  '#2a2a3a',
  accent:  '#7c6dff',
  accent2: '#ff6db0',
  green:   '#4ade80',
  red:     '#f87171',
  yellow:  '#fbbf24',
  text:    '#f0f0f8',
  muted:   '#888899',
} as const;

export const S = {
  card: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  input: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 14,
    color: C.text,
    fontSize: 16,
    marginBottom: 12,
  },
  btnPrimary: {
    backgroundColor: C.accent,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center' as const,
    marginBottom: 10,
  },
  btnSecondary: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center' as const,
    marginBottom: 10,
  },
  btnText: {
    color: C.text,
    fontSize: 16,
    fontWeight: '700' as const,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
    color: C.muted,
    marginBottom: 10,
  },
  muted: { color: C.muted, fontSize: 13 },
} as const;
